[rocks]

[plugins]
"rocks.nvim" = "2.42.4"
"flash.nvim" = "2.1.0"
"which-key.nvim" = "3.17.0"
"rocks-config.nvim" = "3.1.1"
"nvim-tree.lua" = "1.6.0"
"nvim-lspconfig" = "2.3.0"
"lualine.nvim" = "scm"
"nvim-cmp" = "scm"
"cmp-nvim-lsp" = "scm"
"cmp-cmdline" = "scm"
"cmp-buffer" = "scm"
"trouble.nvim" = "3.7.1"
"telescope.nvim" = "scm"
"bufferline.nvim" = "4.9.1"
"conform.nvim" = "9.0.0"
"lazygit.nvim" = "scm"
"typescript-tools.nvim" = "scm"
"snacks.nvim" = "2.22.0"
"nvim-lsp-file-operations" = "scm"
"gitlinker.nvim" = "5.1.0"
"persistence.nvim" = "3.1.0"

[config]
plugins_dir = "plugins/"
auto_setup = false
